name: todo_app_v2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.4.2
  freezed_annotation: ^2.4.1
  freezed: ^2.4.3
  collection: ^1.17.2
  go_router: ^11.1.2
  riverpod_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

scripts:
  build: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner watch